---
abstract: 'Find a file within a set of paths (like @INC or Java classpaths)'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: File::PathList
name: File-PathList
no_index:
  directory:
    - inc
    - t
requires:
  File::Spec: 0.80
  Params::Util: 0.24
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 1.04
